### ISSUE TITLE
只能提示一次

### ISSUE THREAD

**Issue by crossoverJie** [biezhi/gitmoji-plugin#3]
有可能本次提交了两个更新如：
- 升级依赖
- 增加了新特性

如果提交时按照提示输入 `‘依赖’` 可以快速补全，但当换行输入 `‘新特性’` 提示就失效了。

这个场景应该还是蛮常见的，望加入，谢谢。

**Comment by koenhendriks** [comment]
My mandarin is not good, but i think I agree with this issue! 
After entering a newline the plugin becomes inactive. It only works on the first line.

**Comment by hellokaton** [comment]
Next I will pay attention to this problem.

**Comment by bluelovers** [comment]
https://github.com/biezhi/gitmoji-plugin/pull/7

**Comment by crossoverJie** [comment]
fix
