### ISSUE TITLE
:xxx: 只有GitHub和GitLab能够识别

### ISSUE THREAD

**Issue by qiyuey** [biezhi/gitmoji-plugin#9]
:xxx: 这种形式并没有办法被命令行和 Intellij IDEA 支持，建议考虑提供选项支持原生 emoji

**Comment by mingcheng** [comment]
建议增加个配置项，可以选择是否提交原生的 emoji 字符

**Comment by BrikerMan** [comment]
@mingcheng @qiyuey  https://plugins.jetbrains.com/plugin/14610-gitmoji-unicode This plugin supports use the original emoji~
